version: '3.8'

services:
  mongo:
    build:
      context: ./server/mongo        
    
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server       
    container_name: kiruna_backend
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/kiruna   # service name 'mongo'
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    container_name: kiruna_frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:5001   # 👈 runtime backend URL
    depends_on:
      - backend

volumes:
  mongo_data:
