version: '3.8'

services:
  mongo:
    build:
      context: ./mongo        
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./server       
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/kiruna
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"

volumes:
  mongo_data:
